In [1]:
import math
import matplotlib.pyplot as plt
import numpy as np
from disturbances import IntegratedWhiteNoise
import os
from constants import *
from diff_calc import get_mass_matrix
import pandas as pd

In [17]:
J = np.array([[1, 0, -(d_bf-(L_bc/2))],
              [0, -1, -d_ae],
              [1, 0, -d_bf], 
              [0, -1, (d_ad-d_ae)],
              [1, 0, (L_bc - d_bf)],
              [0, -1, (d_ad - d_ae)]])

f_a = 100
phi_a = 0

f_b = 0
phi_b = 0

f_c = 0
phi_c = 0

f = np.array([f_a*np.sin(phi_a), f_a*np.cos(phi_a), 
              f_b*np.sin(phi_b), f_b*np.cos(phi_b), 
              f_c*np.sin(phi_c), f_c*np.cos(phi_c)])


In [21]:
J.transpose()

array([[ 1.        ,  0.        ,  1.        ,  0.        ,  1.        ,
         0.        ],
       [ 0.        , -1.        ,  0.        , -1.        ,  0.        ,
        -1.        ],
       [-0.        , -2.76385399, -1.75      ,  1.381927  ,  1.75      ,
         1.381927  ]])

In [19]:
f

array([  0., 100.,   0.,   0.,   0.,   0.])

In [20]:
J.transpose() @ f

array([   0.       , -100.       , -276.3853992])

In [69]:
f_x = 0
f_y = 100
n = 0

dv = (L_ac + L_bc)/2
J_star = np.array([[1, 0, -(d_bf-(L_bc/2))/dv],
                   [0, -1, -d_ae/dv],
                   [1, 0, -d_bf/dv],
                   [0, -1, (d_ad-d_ae)/dv],
                   [1, 0, (L_bc - d_bf)/dv],
                   [0, -1, (d_ad - d_ae)/dv]])

J_star_plus = J_star @ np.linalg.inv(J_star.T @ J_star)

q_star = np.array([f_x, f_y, n])

In [70]:
J_star_plus @ q_star.T

array([ 0.00000000e+00, -3.33333333e+01, -1.47328174e-15, -3.33333333e+01,
        1.47328174e-15, -3.33333333e+01])

In [71]:
def get_thrust_msgs(input_vec):
    dv = (L_ac + L_bc) / 2
    J_star = np.array([[1, 0, -(d_bf - (L_bc / 2)) / dv],
                       [0, -1, -d_ae / dv],
                       [1, 0, -d_bf / dv],
                       [0, -1, (d_ad - d_ae) / dv],
                       [1, 0, (L_bc - d_bf) / dv],
                       [0, -1, (d_ad - d_ae) / dv]])

    J_star_plus = J_star @ np.linalg.inv(J_star.T @ J_star)
    q_star = input_vec
    return J_star_plus @ q_star.T

In [72]:
get_thrust_msgs(np.array([100, 0, 0]))

array([33.33333333,  0.        , 33.33333333,  0.        , 33.33333333,
        0.        ])